<!DOCTYPE html>
<html lang="ro">
  <head>
    <meta charset="UTF-8" />
    <meta name="description" content="Menagerie on WEB about us" />
    <meta name="author" content="Ivan Remus" />
    <meta name="author" content="Lucaci Alexandru-Constantin" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>About Us</title>

    <link rel="icon" href="views/images/logoBlack.jpg" />

    <link rel="stylesheet" href="views/styles/styleFooter.css" />


    <link rel="stylesheet" href="views/styles/styleAboutPage.css" />
    <link rel="stylesheet" type="text/css" href="views/styles/stylefooter2.css" />
    
    <link rel="stylesheet" href="views/styles/styleNavBar.css" />
    <link rel="stylesheet" href="views/styles/styleSearch.css" />
  
  </head>

  <body>
    <div class="content">
      <?php include("NavBar.phtml") ?>
    </div>


    <br />

    <div class="wrapper">
      <h1>Echipa nopastră</h1>
      <div class="team">
        <div class="team_member">
          <div class="team_img">
            <img src="https://i.imgur.com/2pGPLrl.png" alt="Team_image">
          </div>
          <h3>Paul Doe</h3>
          <p class="role">UI developer</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Est quaerat tempora, voluptatum quas facere dolorum aut cumque nihil nulla harum nemo distinctio quam blanditiis dignissimos.</p>
        </div>
        <div class="team_member">
          <div class="team_img">
            <img src="views/images/LucaciAlex.jpg" alt="Team_image">
          </div>
          <h3>Lucaci Alexandru-Constantin</h3>
          <p class="role">Student</p>
          <p>Mă numesc Alex. Sunt student la Facultatea de Informatică Iași. Perspectivele mele
              sunt îndreptate acum spre consolidarea unei cariere. Sunt o persoană care este
              pasionată atât de tehnologie software cât și de hardware. Cele mai mari calități ale
              mele sunt perseverența și adaptabilitatea, sunt o persoană care se adaptează foarte
              repede la domeniul de lucru și în colective noi. Sunt pasionat de informatică, de
              programare orientată obiect de baze de date( Relational database management
              system) și în ultima perioadă am început să fac și programare funcțională.
          </p>
        </div>
    
    </div>
  </div>

    <?php include("Footer.html") ?>


    <script src="views/javaScript/navBar.js"></script>
  </body>
</html>
