<!DOCTYPE html>
<html lang="ro">
  <head>
    <meta charset="UTF-8" />
    <meta name="description" content="Menagerie on WEB about us" />
    <meta name="author" content="Ivan Remus" />
    <meta name="author" content="Lucaci Alexandru-Constantin" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>About Us</title>

    <link rel="icon" href="views/images/logoBlack.jpg" />

    <link rel="stylesheet" href="views/styles/styleFooter.css" />

    <link rel="stylesheet" href="views/styles/styleSearch.css" />
    <link rel="stylesheet" href="views/styles/styleNavBar.css" />
    <link rel="stylesheet" href="views/styles/styleAboutPage.css" />
    <link rel="stylesheet" type="text/css" href="views/styles/stylefooter2.css" />
  </head>

  <body>
    <div class="content">
      <?php include("NavBar.phtml") ?>
    </div>

    <div class="about-information-grid">
      <div class="about-title">
        <p>Despre noi</p>
      </div>
      <div class="about-info">
        <p>
          Lorem, ipsum dolor sit amet consectetur adipisicing elit.
          Exercitationem nobis sint perferendis. Labore, asperiores ullam enim
          deserunt expedita nemo nostrum illo vero quas explicabo officia?
          Delectus minima asperiores sint facere, ut rem est porro temporibus
          molestias accusantium beatae impedit inventore numquam veniam
          distinctio hic error reprehenderit blanditiis optio. Cumque, eligendi?
        </p>
      </div>
    </div>

    <br />

    <div class="about-team-grid">
      <div class="about-title">
        <p>Intalneste echipa</p>
      </div>

      <div class="about-cards-grid">
        <div class="about-card-grid">
          <div class="about-card-container1">
            <img src="views/images/unknownPerson.jpg" alt="unknown person" />
            <div class="about-card-title">
              <p>Lucaci Alexandru-Constantin</p>
              <p>Web developer</p>
            </div>
          </div>

          <div class="about-card-info">
            <p>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsam
              debitis officia placeat, eos consectetur, voluptatibus voluptate
              nobis cumque totam dolor ad reiciendis quidem neque sapiente odio
              sint itaque. Aperiam, inventore.
            </p>
          </div>
        </div>

        <div class="about-card-grid">
          <div class="about-card-container1">
            <img src="views/images/unknownPerson.jpg" alt="unknown person" />
            <div class="about-card-title">
              <p>Ivan Remus</p>
              <p>Web developer</p>
            </div>
          </div>

          <div class="about-card-info">
            <p>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit.
              Voluptatem, laborum libero cumque nostrum blanditiis neque quis,
              amet odit saepe tenetur magnam iste hic vero quos sed quibusdam
              eius tempora necessitatibus!
            </p>
          </div>
        </div>
      </div>
    </div>

    <?php include("Footer.html") ?>


    <script src="views/javaScript/navBar.js"></script>
  </body>
</html>
