<!DOCTYPE html>
<html lang="ro">
    <head>
        <title>Administrare formulare de contact</title>       
         <title>Administrare utilizatori</title>
        <link rel="stylesheet" type="text/css" href="views/styles/styleNavBar.css" />
        <link rel="stylesheet" type="text/css" href="views/styles/stylefooter2.css" />
        <link rel="stylesheet" type="text/css" href="views/styles/styleSearch.css" />
        <link rel="stylesheet" type="text/css" href="views/styles/styleSettings.css" />
        <!-- <link rel="stylesheet" type="text/css" href="views\styles\styleAdminForms.css" /> -->
        <link rel="stylesheet" href="views/styles/styleButtons.css" />
    </head>

    <body>

    <?php include("AdminUpdate.php"); ?>
    
    <?php
        echo "<div class=\"main-navbar-container\">";
            include("NavBar.phtml"); 
        echo "</div>";

        echo "<div class=\"wrapper\">";
            echo "<div class=\"left\">";
                echo "<h4>$username</h4>";
                echo "<div class =\"links\">";
                    include("AccountNavBar.phtml");
                echo "</div>";
            echo "</div>";
    ?>
    <div class = "mainClass">
    <div class="right">
    <div>
        <div class="info">
                <h3>Formulare de contact</h3>
            </div>
       

        <div>
            <div class="info">
                <h3>Reîncarcă rezultatele</h3>
            </div>
       
        
            <form action="index.php" method="post">
                <input type="hidden" name="load" value="AdminForms/update" />
                <input type="hidden" name="function" value="get_forms" />
                <br>
                    <div class="projects_data">
                        
                    <input type="submit" value="Reincarca" class="filtbutt" />
                        
                    </div>  
                <br>
              
            


            </form>
        </div>

    </div>

    <div>
        <?php
            if(isset($_SESSION['admin']['list_forms'])&&!empty($_SESSION['admin']['list_forms'])){

                echo "<div>";
                    echo "<form action=\"index.php\" method=\"post\">";
                        echo "<input type=\"hidden\" name=\"load\" value=\"AdminForms/update\" />";
                        echo "<input type=\"hidden\" name=\"function\" value=\"change_form_position\" />";
                        echo "<input type=\"hidden\" name=\"change_value\" value=\"-1\" />";
        
                        echo "
                        <br>
                        <div class=\"projects_data\">
                            
                            <input type=\"submit\" value=\"Formularul anterior\" class=\"filtbutt\"/>
                            
                        </div>  
                        <br>";
        
                    echo "</form>";
                echo "</div>";

                echo "<div>";
                    echo "<form action=\"index.php\" method=\"post\">";
                        echo "<input type=\"hidden\" name=\"load\" value=\"AdminForms/update\" />";
                        echo "<input type=\"hidden\" name=\"function\" value=\"change_form_position\" />";
                        echo "<input type=\"hidden\" name=\"change_value\" value=\"1\" />";
                        echo "
                        <br>
                        <div class=\"projects_data\">
                            
                             <input type=\"submit\" value=\"Formularul urmator\" class=\"filtbutt\"/>
                            
                        </div>  
                        <br>";

                        
                    echo "</form>";
                echo "</div>";
                
                $forms=$_SESSION['admin']['list_forms'];
                $position=$_SESSION['admin']['form_position'];

                $name=htmlentities($forms[$position]['NUME']);
                if(empty($name)){
                    $name='-';
                }

                $email=htmlentities($forms[$position]['EMAIL']);
                if(empty($email)){
                    $email='-';
                }

                $telephone=htmlentities($forms[$position]['TELEFON']);
                if(empty($telephone)){
                    $telephone='-';
                }

                $message=htmlentities($forms[$position]['MESAJ']);
                if(empty($message)){
                    $message='-';
                }

                echo "<div>";
                    echo "
                    <div class=\"info\">
                        <h3>Informații formular de contact:</h3>
                    </div>";
                    echo "
                    <div class=\"projects_data\">
                    <div class=\"data\">
                        <h4><label>Nume:$name</label></h4>
                        <h4><label>Email:$email</label></h4>
                        <h4><label>Numar de telefon:$telephone</label></h4>
                        <h4><label>Mesaj:$message</label></h4>
                         />
                    </div>
                    </div>";
                echo "</div>";

            }
            else{

                echo "
                <div class=\"projects_data\">
                <div class=\"data\">
                    <h4><label>Nimic de aratat</label></h4>
              
                    </div>
                 </div>";
                
            }
        ?>
    </div>
    </div>
    </div>

    </body>
</html>
