<!DOCTYPE html>
<html lang="ro">
    <head>
        <title>Administrare animale</title>
        <link rel="stylesheet" type="text/css" href="views/styles/styleNavBar.css" />
        <link rel="stylesheet" type="text/css" href="views/styles/stylefooter2.css" />
        <link rel="stylesheet" type="text/css" href="views/styles/styleSearch.css" />
        <link rel="stylesheet" type="text/css" href="views/styles/styleSettings.css" />
        <link rel="stylesheet" type="text/css" href="views/styles/styleAdminAnimals.css" />
        <link rel="stylesheet" href="views/styles/styleButtons.css" />
    </head>
    <body>

    <?php include("AdminUpdate.php"); ?>
    
    <?php
        echo "<div class=\"main-navbar-container\">";
            include("NavBar.phtml"); 
        echo "</div>";
        echo "
        <div class=\"wrapper\"><div class=\"left\">
          <h4>$username</h4>";
       

        echo "<h4> <div class =\"links\">";
        include("AccountNavBar.phtml");
        echo "</div></h4>
        </div>";
    ?>;
    
    <div class="mainClass">

        <div class="right">
            <div class="info">
                <h3>Animale</h3>
            </div>
        <div>
       
            <div class="info">
                <h3>Găsește animalele după nume și  valoare </h3>
            </div>
            
           
            <form action="index.php" method="post">
                <input type="hidden" name="load" value="AdminAnimals/update" />
                <input type="hidden" name="function" value="get_information" />
                <input type="hidden" name="table" value="animale" />

                <div class="projects_data">
                    <div class="data">
                        <h4><label for="field_name">Nume câmp</label><h4>
                        <input type="text" name="field_name" maxlength="30" />
                    </div>
                </div>
                <div class="projects_data">
                    <div class="data">
                        <h4><label for="field_value">Valoare câmp</label></h4>
                        <input type="text" name="field_value" maxlength="30" />
                    </div>
             
                </div>  
                <br>
                <div class="projects_data">
                    
                    <input type="submit" value="Gaseste" class="filtbutt" />
                    
                </div>  
                <br>
            </form>

        </div>

        <div>
            <div class="info">
                <h3>Listă animale: </h3>
            </div>
            <div class="projects_data">
                <?php 
                    //echo "<pre>";
                    //print_r($data);
                    //echo "</pre>";
                ?>

            </div>  

        </div>

        <div>
            <div class="info">
                <h3>Obține valoare câmp pentru un animal </h3>
            </div>
            <form action="index.php" method="post">
                <input type="hidden" name="load" value="AdminAnimals/update" />
                <input type="hidden" name="function" value="get_animal_field_value" />

                <div class="projects_data">
                    <div class="data">
                        <h4><label for="animal_name">Nume animal</label></h4>
                        <input type="text" name="animal_name" />
                    </div>
                </div> 
                <div class="projects_data">
                    <div class="data">
                        <h4><label for="field_name">Nume camp</label></h4>
                        <input type="" name="field_name" />     
                    </div>
                </div>
                <br>
                <div class="projects_data">
                    
                    <input type="submit" value="Gaseste" class ="filtbutt"/>
                   
                </div>
                <br>

                 

            </form>
            <div>
                <?php 
                    $value='';
                    if(isset($_SESSION['admin']['animal_info'])){
                        $value=$_SESSION['admin']['animal_info']['field_value'];
                    }
                    if(empty($value)){
                        $value='-';
                    }

                    echo "<h4><p>Valoare:$value</p></h4>";                    
                ?>
            </div>
        </div>

        <div>
            <div class="info">
                <h3>Schimbă valoare pentru un animal</h3>
            </div>
            
            <form action="index.php" method="post">
                <input type="hidden" name="load" value="AdminAnimals/update" />
                <input type="hidden" name="function" value="change_animal_field_value" />



                
                <div class="projects_data">
                    <div class="data">
                        <h4><label for="animal_name">Nume animal</label></h4>
                        <input type="text" name="animal_name" />
                    </div>
                </div> 

                <div class="projects_data">
                    <div class="data">
                        <h4><label for="field_name">Nume camp schimbat</label></h4>
                        <input type="" name="field_name" /> 
                    </div>
                </div>
                <div class="projects_data">
                    <div class="data">
                        <h4><label for="field_value">Valoare noua</label></h4>
                        <input type="" name="field_value" />
                    </div>
                </div>  
                <br>
                <div class="projects_data"> 
                    <input type="submit" value="Schimba" class ="filtbutt"/>
                </div>
                <br>

               
            </form>
        </div>

        <div>

            <div class="info">
                <h3>Obține utilizatori care salvează acest animal </h3>
            </div>        
            
            <form action="index.php" method="post">
                <input type="hidden" name="load" value="AdminAnimals/update" />
                <input type="hidden" name="function" value="get_animal_saved_by_users" />

               

                <div class="projects_data">
                    <div class="data">
                        <h4><label for="animal_name">Nume animal</label></h4>
                        <input type="text" name="animal_name" />
                    </div>
                </div>  
                <br>
                <div class="projects_data"> 
                    <input type="submit" value="Obtine" class ="filtbutt"/>
                </div>
                <br>


                
            </form>
        </div>

        <div>
            <div class="info">
                <h3>Șterge un animal </h3>
            </div> 
            
            <form action="index.php" method="post">

                

                <input type="hidden" name="load" value="AdminAnimals/update" />
                <input type="hidden" name="function" value="delete_animal" />

                <div class="projects_data">
                    <div class="data">
                        <h4><label for="animal_name">Nume animal</label><h4>
                        <input type="text" name="animal_name" />
                    </div>
                </div>  
                <br>
                <div class="projects_data"> 
                     <input type="submit" value="Sterge" class ="filtbutt" />
                </div>
                <br>

                

                
            </form>
        </div>
    </div>
<script src="views/javascript/navBar.js"></script>
    </body>
</html>
