<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Administrare</title>
    </head>
    <body>

    <?php
        if(is_array($data)){

            echo "<pre>";
            print_r($data);
            echo "</pre>";

            //update session variables in case of request
            $toBeUpdated=array('user_info','animal_info','list_users','list_animals','users_saved_animals','animal_saved_by_users','field_value');
            foreach($toBeUpdated as $name){
                if(isset($data[$name])){
                    $_SESSION['admin'][$name]=$data[$name];
                    echo "in:$name<br>";
                }
                else{
                    echo "out:$name<br>";
                }
            }
        }
        else{
            echo "<h3>$data</h3>";
        }
    ?>
    <?php
        include("NavBar.phtml"); 
    
        include("AccountNavBar.phtml") 
    ?>;

    <div>
        <h2>Utilizatori</h2>

        <div>
            <p>Gaseste utilizatori dupa nume camp si valoare camp</p>
            <form action="index.php" method="post">
                <input type="hidden" name="load" value="Admin/update" />
                <input type="hidden" name="function" value="get_information" />
                <input type="hidden" name="table" value="utilizatori" />

                <label for="field_name">Nume camp</label>
                <input type="text" name="field_name" maxlength="30" />

                <label for="field_value">Valoare camp</label>
                <input type="text" name="field_value" maxlength="30" />

                <input type="submit" />
            </form>
        </div>

        <div>
            <p>Lista utilizatori:</p>
            <?php 
                //echo "<pre>";
                //print_r($data);
                //echo "</pre>";
            ?>
        </div>

        <hr>

        <div>
            <p>Obtine informatiile despre utilizator</p>
            <form action="index.php" method="post">
                <input type="hidden" name="load" value="Admin/update" />
                <input type="hidden" name="function" value="get_user_information" />
                <input type="text" name="username" />

                <input type="submit" value="Obtine informatii utilizator" />
            </form>
            <h4>Informatii utilizator</h4>
            <?php
                if(isset($_SESSION['admin']['user_info'])&&!empty($_SESSION['admin']['user_info'])){

                    $username=htmlentities($_SESSION['admin']['user_info']['NUME_UTILIZATOR']);
                    $password=htmlentities($_SESSION['admin']['user_info']['PAROLA']);
    
                    $email=htmlentities($_SESSION['admin']['user_info']['EMAIL']);
                    if(is_null($email)||empty($email)){
                        $email='-';
                    }
    
                    $cellphone=htmlentities($_SESSION['admin']['user_info']['TELEFON']);
                    if(is_null($cellphone)||empty($cellphone)){
                        $cellphone='-';
                    }

                    $isAdmin=htmlentities($_SESSION['admin']['user_info']['ADMINISTRATOR']);
                    $isAdmin=($isAdmin==0)?"Nu":"Da";

                    echo "<p>Nume utilizator:$username</p>";
                    echo "<p>Parola:$password</p>";
                    echo "<p>Email:$email</p>";
                    echo "<p>Numar de telefon:$cellphone</p>";
                    echo "<p>Este administrator:$isAdmin</p>";                    
                }
                else{
                    echo "<p>Nimic de afisat</p>";
                } 
            ?>
        </div>
        
        <hr>

        <div>
            <p>Schimba informatiile despre un utilizator</p>
            <form action="index.php" method="post">
                <input type="hidden" name="load" value="Admin/update" />
                <input type="hidden" name="function" value="change_account_information" />
                
                <label for="username">Nume utilizator:</label>
                <input type="text" name="username" />
                
                <label for="field_name">Nume camp</label>
                <input type="text" name="field_name" />

                <label for="field_value">Valoare noua a campului</label>
                <input type="text" name="field_value" />

                <input type="submit" value="Modifica camp" />
            </form>
        </div>

        <div>
            <p>Sterge un utilizator</p>
            <form action="index.php" method="post">
                <input type="hidden" name="load" value="Admin/update" />
                <input type="hidden" name="function" value="delete_account" />

                <label for="username">Nume utilizator:</label>
                <input type="text" name="username" />

                <input type="submit" value="Sterge cont" />
            </form>
        </div>

        <hr>

        <div>
            <p>Vezi salvarile unui utilizator</p>
            <div>
                <form action="index.php" method="post">
                    <input type="hidden" name="load" value="Admin/update" />
                    <input type="hidden" name="function" value="get_saved_animals" />

                    <label for="username">Nume utilizator:</label>
                    <input type="text" name="username" />
                
                    <input type="submit" value="Obtine salvari" />

                </form>
            </div>
            <div>
                <h3>Salvarile:</h3>
                <?php 
                    if(isset($_SESSION['admin']['users_saved_animals'])&&!empty($_SESSION['admin']['users_saved_animals'])){

                        $listAnimals=$_SESSION['admin']['users_saved_animals'];

                        if(empty($listAnimals)){
                            echo "<p>Niciun animal salvat</p>";
                        }
                        else{
                            $position=1;
                            foreach($listAnimals as $animal){
                                
                                $popularName=$animal['DENUMIRE_POPULARA'];
                                $scientificName=$animal['DENUMIRE_STINTIFICA'];

                                echo "<p>$position : $popularName,$scientificName</p>";
                                echo "<hr>";

                                $position++;
                            }
                        }          
                    }
                    else{
                        echo "<p>Nimic de afisat</p>";
                    } 
                ?>
            </div>

        </div>

    </div>

    <?php include("Footer.html"); ?>

    </body>
</html>
