<!DOCTYPE html>
<html lang="ro">
    <head>
        <title>Administrare animale</title>
    </head>
    <body>

    <?php include("AdminUpdate.php"); ?>

    <?php
        include("NavBar.phtml"); 
    
        include("AccountNavBar.phtml") 
    ?>;
    
    <div>
        <h2>Animale</h2>

        <div>
            <p>Gaseste animale dupa nume camp si valoare camp</p>
            <form action="index.php" method="post">
                <input type="hidden" name="load" value="AdminAnimals/update" />
                <input type="hidden" name="function" value="get_information" />
                <input type="hidden" name="table" value="animale" />

                <label for="field_name">Nume camp</label>
                <input type="text" name="field_name" maxlength="30" />

                <label for="field_value">Valoare camp</label>
                <input type="text" name="field_value" maxlength="30" />

                <input type="submit" value="Gaseste" />
            </form>
        </div>

        <div>
            <p>Lista animale:</p>
            <?php 
                //echo "<pre>";
                //print_r($data);
                //echo "</pre>";
            ?>
        </div>

        <div>
            <p>Obtine valoare camp pentru un animal</p>
            <form action="index.php" method="post">
                <input type="hidden" name="load" value="AdminAnimals/update" />
                <input type="hidden" name="function" value="get_animal_field_value" />

                <label for="animal_name">Nume animal</label>
                <input type="text" name="animal_name" />

                <label for="field_name">Nume camp</label>
                <input type="" name="field_name" />

                <input type="submit" value="Gaseste" />
            </form>
            <div>
                <?php 
                    $value='';
                    if(isset($_SESSION['admin']['animal_info'])){
                        $value=$_SESSION['admin']['animal_info']['field_value'];
                    }
                    if(empty($value)){
                        $value='-';
                    }

                    echo "<p>Valoare:$value</p>";                    
                ?>
            </div>
        </div>

        <div>
            <p>Schimba valoare camp pentru un animal</p>
            <form action="index.php" method="post">
                <input type="hidden" name="load" value="AdminAnimals/update" />
                <input type="hidden" name="function" value="change_animal_field_value" />

                <label for="animal_name">Nume animal</label>
                <input type="text" name="animal_name" />

                <label for="field_name">Nume camp schimbat</label>
                <input type="" name="field_name" />

                <label for="field_value">Valoare noua</label>
                <input type="" name="field_value" />

                <input type="submit" value="Schimba" />
            </form>
        </div>

        <div>
            <p>Obtine utilizatori care salveaza acest animal</p>
            <form action="index.php" method="post">
                <input type="hidden" name="load" value="AdminAnimals/update" />
                <input type="hidden" name="function" value="get_animal_saved_by_users" />

                <label for="animal_name">Nume animal</label>
                <input type="text" name="animal_name" />

                <input type="submit" value="Obtine" />
            </form>
        </div>

        <div>
            <p>Sterge un animal</p>
            <form action="index.php" method="post">
                <input type="hidden" name="load" value="AdminAnimals/update" />
                <input type="hidden" name="function" value="delete_animal" />

                <label for="animal_name">Nume animal</label>
                <input type="text" name="animal_name" />

                <input type="submit" value="Sterge" />
            </form>
        </div>
    </div>

    <?php include("Footer.html"); ?>

    </body>
</html>
