<!DOCTYPE html>
<html lang="ro">
    <head>
        <title>Administrare utilizatori</title>
        <link rel="stylesheet" type="text/css" href="views/styles/styleNavBar.css" />
        <link rel="stylesheet" type="text/css" href="views/styles/stylefooter2.css" />
        <link rel="stylesheet" type="text/css" href="views/styles/styleSearch.css" />
        <link rel="stylesheet" type="text/css" href="views/styles/styleSettings.css" />
        <link rel="stylesheet" type="text/css" href="views/styles/styleAdminUtilizator.css" />
        <link rel="stylesheet" href="views/styles/styleButtons.css" />
    </head>
    <body>

    <?php include("AdminUpdate.php"); ?>

    <?php
        include("NavBar.phtml"); 
    
        echo "<div class=\"wrapper\">";
            echo "<div class=\"left\">";
                echo "<h4>$username</h4>";
                echo "<div class =\"links\">";
                    include("AccountNavBar.phtml");
                echo "</div>";
            echo "</div>";
    ?>

    <div class="mainClass">
        <div class="right">
            <div class="info">
                <h3>Utilizatori</h3>
            </div>
       
            <div>
                <div class="info">
                    <h3>Găsește utilizatori după nume câmp și valoare câmp</h3>
                </div>
            
                <form action="index.php" method="post">
                    <input type="hidden" name="load" value="AdminUsers/update" />
                    <input type="hidden" name="function" value="get_information" />
                    <input type="hidden" name="table" value="utilizatori" />

                    <div class="projects_data">
                        <div class="data">
                            <h4><label>Nume câmp</label></h4>
                            <input type="text" name="field_name" maxlength="30" />
                        </div>
                    </div>

                    <div class="projects_data">
                        <div class="data">
                            <h4><label>Valoare câmp</label></h4>
                            <input type="text" name="field_value" maxlength="30" />
                        </div>
                    </div>
                    <br>
                    <div class="projects_data">
                        
                        <input type="submit" value="Găsește" class="filtbutt" />
                        
                    </div>  
                    <br>
                </form>
            </div>

        <div>
            <div class="info">
                <h3>Listă utilizatori: </h3>
            </div>
            <div class="projects_data">
                <?php 
                    //echo "<pre>";
                    //print_r($data);
                    //echo "</pre>";
                ?>

            </div>  
        </div>

        <!-- <hr>  -->

        <div>
            <div class="info">
                <h3>Obține informațiile despre utilizator</h3>
            </div>
            
            <form action="index.php" method="post">
                <input type="hidden" name="load" value="AdminUsers/update" />
                <input type="hidden" name="function" value="get_user_information" />
                <div class="projects_data">
                    <div class="data">
                        <h4><label>Nume</label></h4>
                        <input type="text" name="username" />   
                    </div>
                </div>
                <br>
                <div class="projects_data">
                    
                <input type="submit" value="Obtine informatii utilizator" class ="filtbutt"/>
                   
                </div>
                <br>

                 
            </form>
            <div class="info">
                <h3>Informații utilizator</h3>
            </div>
            
            <?php
                if(isset($_SESSION['admin']['user_info'])&&!empty($_SESSION['admin']['user_info'])){

                    $info=$_SESSION['admin']['user_info']['0'];

                    $username=htmlentities($info['NUME_UTILIZATOR']);
                    $password=htmlentities($info['PAROLA']);
    
                    $email=htmlentities($info['EMAIL']);
                    if(is_null($email)||empty($email)){
                        $email='-';
                    }
    
                    $cellphone=htmlentities($info['TELEFON']);
                    if(is_null($cellphone)||empty($cellphone)){
                        $cellphone='-';
                    }

                    $isAdmin=htmlentities($info['ADMINISTRATOR']);
                    $isAdmin=($isAdmin==0)?"Nu":"Da";
                    
                    echo "
                        <div class=\"projects_data\">
                            <div class=\"data\">";
                            echo "<p>Nume utilizator:$username</p>";
                            echo "<p>Parola:$password</p>";
                            echo "<p>Email:$email</p>";
                            echo "<p>Numar de telefon:$cellphone</p>";
                            echo "<p>Este administrator:$isAdmin</p>";    
                    echo "  </div>
                        </div>";


                    // echo "<p>Nume utilizator:$username</p>";
                    // echo "<p>Parola:$password</p>";
                    // echo "<p>Email:$email</p>";
                    // echo "<p>Numar de telefon:$cellphone</p>";
                    // echo "<p>Este administrator:$isAdmin</p>";                    
                }
                else{
                    echo "<p>Nimic de afisat</p>";
                } 
            ?>
        </div>
        
        <hr>

        <div>
            <div class="info">
                <h3>Schimbă informațiile despre un utilizator</h3>
            </div>
            
            <form action="index.php" method="post">
                <input type="hidden" name="load" value="AdminUsers/update" />
                <input type="hidden" name="function" value="change_account_information" />
                
                <div class="projects_data">
                    <div class="data">
                       <h4> <label>Nume utilizator:</label></h4>
                        <input type="text" name="username" />
                    </div>
                </div> 

                <div class="projects_data">
                    <div class="data">
                        <h4><label>Nume câmp</label></h4>
                        <input type="text" name="field_name" />
                    </div>
                </div> 
                
                <div class="projects_data">
                    <div class="data">
                        <h4><label>Valoare nouă a câmpului</label></h4>
                        <input type="text" name="field_value" />
                    </div>
                </div> 

                <br>
                <div class="projects_data"> 
                    <input type="submit" value="Modifică camp" class ="filtbutt" />
                </div>
                <br>


                
            </form>
        </div>

        <div>
            <div class="info">
                <h3>Șterge un utilizator </h3>
            </div> 
            <form action="index.php" method="post">
                <input type="hidden" name="load" value="AdminUsers/update" />
                <input type="hidden" name="function" value="delete_account" />

                
                <div class="projects_data">
                    <div class="data">
                        <h4><label>Nume utilizator:</label></h4>
                        <input type="text" name="username" />
                    </div>
                </div>  
                <br>
                <div class="projects_data"> 
                    <input type="submit" value="Șterge cont" class ="filtbutt" />
                </div>
                <br>

            </form>
        </div>

        <hr>

        <div>
            <div class="info">
                <h3>Vezi salvările unui utilizator </h3>
            </div>
        
            <div>
                <form action="index.php" method="post">
                    <input type="hidden" name="load" value="AdminUsers/update" />
                    <input type="hidden" name="function" value="get_saved_animals" />


                    <div class="projects_data">
                        <div class="data">
                            <h4><label>Nume utilizator:</label></h4>
                            <input type="text" name="username" />
                        </div>
                    </div>  
                    <br>
                    <div class="projects_data"> 
                        <input type="submit" value="Obține salvari" class ="filtbutt" />
                    </div>
                    <br>

                   
                

                </form>
            </div>
            <div>
                <div class="info">
                    <h3>Salvările </h3>
                </div>
               
                <?php 
                    if(isset($_SESSION['admin']['users_saved_animals'])&&!empty($_SESSION['admin']['users_saved_animals'])){

                        $listAnimals=$_SESSION['admin']['users_saved_animals'];

                        if(empty($listAnimals)){
                            echo "<div class=\"projects_data\">
                                    <div class=\"data\"";
                                    echo "<p>Niciun animal salvat</p>";
                            echo "</div>
                            </div>";
                        }
                        else{
                            $position=1;
                            echo "<div class=\"projects_data\">
                                    <div class=\"data\"";
                            foreach($listAnimals as $animal){
                                
                                $popularName=$animal['DENUMIRE_POPULARA'];
                                $scientificName=$animal['DENUMIRE_STINTIFICA'];

                                echo "<p>$position : $popularName,$scientificName</p>";
                                // echo "<hr>";

                                $position++;
                            }
                            echo "</div>
                            </div>";
                        }          
                    }
                    else{
                        echo "<div class=\"projects_data\">";
                            echo "<div class=\"data\">";
                            echo "<p>Nimic de afisat</p>";
                            echo "</div>";
                        echo "</div>";
                    } 
                ?>
            </div>

        </div>

    </div>
    </div>
    <script src="views/javascript/navBar.js"></script>
    </body>
</html>
