<!DOCTYPE html>

<html lang="ro">
  <head>
    <meta charset="UTF-8" />
    <meta name="description" content="Menagerie on WEB" />
    <meta
      name="keywords"
      content="Menagerie on Web, MeoW, ZOO, zoo, TW proiect, 2B2 "
    />
    <meta name="author" content="Ivan Remus" />
    <meta name="author" content="Lucaci Alexandru-Constantin" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Menagerie on Web</title>

    <link rel="icon" href="views/images/logoBlack.jpg" />
    <link rel="stylesheet" href="views/styles/styleSearch.css" />
    <link rel="stylesheet" href="views/styles/styleNavBar.css" />
    <link rel="stylesheet" href="views/styles/styleAnimals.css" />
    <link rel="stylesheet" href="views/styles/filterlist.css" />
    <link rel="stylesheet" href="views/styles/styleFooter.css" />
  </head>

  <body>
    <div class="gridBody">
      <div class="content">
        <?php include("NavBar.phtml") ?>
      </div>

      <div class="main">
        <div class="filterBar">
          <div class="butt">
            <button class="filtbutt" onclick="functionButt()">
              Filtru animale
            </button>
          </div>
          <div class="filtre" id="myDIV">
            <!-- <ul class="todos" id="todos"> -->
            <div class="categorieFiltru">
              <ul class="todos" id="todos_00">
                <li>
                  <div class="toggler">Ordonare</div>
                  <ul class="toggler-target active">
                    <li class="todo active">Alfabetica</li>
                  </ul>
                </li>
              </ul>
              <br />
            </div>
            <div class="categorieFiltru">
              <ul class="todos" id="todos_0">
                <li>
                  <div class="toggler">Categorie(clase de animale)</div>
                  <ul class="toggler-target active">
                    <li class="todo active">toate</li>
                    <li class="todo">amfibieni</li>
                    <li class="todo">arahnide</li>
                    <li class="todo">asteroidea</li>
                    <li class="todo">bivalve</li>
                    <li class="todo">chefalopode</li>
                    <li class="todo">chilopoda</li>
                    <li class="todo">diplopoda</li>
                    <li class="todo">gasteropode</li>
                    <li class="todo">hydroza</li>
                    <li class="todo">insecte</li>
                    <li class="todo">malacostraca</li>
                    <li class="todo">mamifere</li>
                    <li class="todo">ostracode</li>
                    <li class="todo">păsari</li>
                    <li class="todo">pești</li>
                    <li class="todo">polichete</li>
                    <li class="todo">reptile</li>
                  </ul>
                </li>
              </ul>
              <br />
            </div>
            <div class="categorieFiltru">
              <ul class="todos" id="todos_1">
                <li>
                  <div class="toggler">Origine</div>
                  <ul class="toggler-target active">
                    <li class="todo active">toate</li>
                    <li class="todo">Asia</li>
                    <li class="todo">Africa</li>
                    <li class="todo">Europa</li>
                    <li class="todo">Australia</li>
                    <li class="todo">America de Nord</li>
                    <li class="todo">America de Sud</li>
                    <li class="todo">Antartica</li>
                  </ul>
                </li>
              </ul>
              <br />
            </div>
            <div class="categorieFiltru">
              <ul class="todos" id="todos_2">
                <li>
                  <div class="toggler">Statut</div>
                  <ul class="toggler-target active">
                    <li class="todo active">Toate</li>
                    <li class="todo">protejată</li>
                    <li class="todo">pe cale de dispariție</li>
                    <li class="todo">dăunătoare</li>
                  </ul>
                </li>
              </ul>
              <br />
            </div>
            <div class="categorieFiltru">
              <ul class="todos" id="todos_3">
                <li>
                  <div class="toggler">Specii inrudite</div>
                  <ul class="toggler-target active">
                    <li class="todo active">da</li>
                    <li class="todo">nu</li>
                  </ul>
                </li>
              </ul>
              <br />
            </div>

            <div class="categorieFiltru">
              <ul class="todos" id="todos_4">
                <li>
                  <div class="toggler">Regim alimentar</div>
                  <ul class="toggler-target active">
                    <li class="todo active">toate</li>
                    <li class="todo">ierbivor</li>
                    <li class="todo">carnivor</li>
                    <li class="todo">omnivor</li>
                  </ul>
                </li>
              </ul>
              <br />
            </div>
            <!-- </ul> -->
            <div class="categorieFiltru">
              <ul class="todos" id="todos_5">
                <li>
                  <div class="toggler">Mod de inmulțire</div>
                  <ul class="toggler-target active">
                    <li class="todo active">toate</li>
                    <li class="todo">monocitogenă</li>
                    <li class="todo">bisexuală</li>
                    <li class="todo">asexuală</li>
                  </ul>
                </li>
              </ul>
              <br />
            </div>
          </div>
        </div>
        <div class="itemsContent">
          <div class="rightplace">
            <div class="card">
              <img
                src="views/images/animals1.jpg"
                alt="Imagine animal 1"
                class="card-img"
              />
              <h2 class="card-title">Panthera tigris</h2>
              <div class="card-content">
                <p>
                  Tigrilor le sunt caracteristice dungile de culoare închisă,
                  amplasarea cărora variază de la un individ la altul. Corpul
                  este adaptat pentru vânătoare, fiind dotat cu colți lungi și
                  maxilare puternice, vedere nocturnă de șase ori mai bună decât
                  a omului și musculatură dezvoltată, fiind capabil să sară la o
                  înălțime de până la doi metri cu 50 kg de carne în dinți.
                </p>
                <a href="#">Mai multe </a>
              </div>
            </div>
            <div class="card">
              <img
                src="views/images/animals2.jpg"
                alt="Imagine animal suricata"
                class="card-img"
              />
              <h2 class="card-title">Suricata suricatta</h2>
              <div class="card-content">
                <p>
                  Suricata (mangusta cu 4 degete) (denumirea științifică
                  Suricata suricatta) este un mamifer mic și un membru al
                  familiei mangustelor. Ea trăiește peste tot în Deșertul
                  Kalahari, în Botswana și în Africa de Sud. Un grup de suricate
                  este numit „gloată”, „ceată” sau „colonie”. Suricatele au
                  media de viață în jur de 10 ani.
                </p>
                <a href="#">Mai multe </a>
              </div>
            </div>
            <div class="card">
              <img
                src="views/images/animals3.jpg"
                alt="Imagine animal flamingo"
                class="card-img"
              />
              <h2 class="card-title">Phoenicopterus</h2>
              <div class="card-content">
                <p>
                  Pasărea flamingo este impresionantă din punct de vedere al
                  aspectului, având un colorit spectaculos. Din acest motiv,
                  pasărea flamingo este foarte populară în lumea întreagă,
                  imaginea ei fiind adesea imprimată pe haine și și accesorii.
                  Citeşte întreaga ştire: Pasărea flamingo - Curiozități și
                  lucruri mai puțin știute
                </p>
                <a href="#">Mai multe </a>
              </div>
            </div>
            <div class="card">
              <img
                src="views/images/animals1.jpg"
                alt="Imagine animal 1"
                class="card-img"
              />
              <h2 class="card-title">nume stiintific</h2>
              <div class="card-content">
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo,
                  odio. Sequi rerum soluta explicabo et dolore aliquid,
                  repellendus rem veritatis, delennctio corrupti? Blanditiis
                  ratione iste soluta dolorum vero!
                </p>
                <a href="#">Mai multe </a>
              </div>
            </div>
            <div class="card">
              <img
                src="views/images/animals1.jpg"
                alt="Imagine animal 1"
                class="card-img"
              />
              <h2 class="card-title">nume stiintific</h2>
              <div class="card-content">
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo,
                  odio. Sequi rerum soluta explicabo et dolore aliquid,
                  repellendus rem veritatis, delennctio corrupti? Blanditiis
                  ratione iste soluta dolorum vero!
                </p>
                <a href="#">Mai multe </a>
              </div>
            </div>
            <div class="card">
              <img
                src="views/images/animals1.jpg"
                alt="Imagine animal 1"
                class="card-img"
              />
              <h2 class="card-title">nume stiintific</h2>
              <div class="card-content">
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo,
                  odio. Sequi rerum soluta explicabo et dolore aliquid,
                  repellendus rem veritatis, delennctio corrupti? Blanditiis
                  ratione iste soluta dolorum vero!
                </p>
                <a href="#">Mai multe </a>
              </div>
            </div>
            <div class="card">
              <img
                src="views/images/animals1.jpg"
                alt="Imagine animal 1"
                class="card-img"
              />
              <h2 class="card-title">nume stiintific</h2>
              <div class="card-content">
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo,
                  odio. Sequi rerum soluta explicabo et dolore aliquid,
                  repellendus rem veritatis, delennctio corrupti? Blanditiis
                  ratione iste soluta dolorum vero!
                </p>
                <a href="#">Mai multe </a>
              </div>
            </div>
            <div class="card">
              <img
                src="views/images/animals1.jpg"
                alt="Imagine animal 1"
                class="card-img"
              />
              <h2 class="card-title">nume stiintific</h2>
              <div class="card-content">
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo,
                  odio. Sequi rerum soluta explicabo et dolore aliquid,
                  repellendus rem veritatis, delennctio corrupti? Blanditiis
                  ratione iste soluta dolorum vero!
                </p>
                <a href="#">Mai multe </a>
              </div>
            </div>
            <div class="card">
              <img
                src="views/images/animals1.jpg"
                alt="Imagine animal 1"
                class="card-img"
              />
              <h2 class="card-title">nume stiintific</h2>
              <div class="card-content">
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo,
                  odio. Sequi rerum soluta explicabo et dolore aliquid,
                  repellendus rem veritatis, delennctio corrupti? Blanditiis
                  ratione iste soluta dolorum vero!
                </p>
                <a href="#">Mai multe </a>
              </div>
            </div>
            <div class="card">
              <img
                src="views/images/animals1.jpg"
                alt="Imagine animal 1"
                class="card-img"
              />
              <h2 class="card-title">nume stiintific</h2>
              <div class="card-content">
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo,
                  odio. Sequi rerum soluta explicabo et dolore aliquid,
                  repellendus rem veritatis, delennctio corrupti? Blanditiis
                  ratione iste soluta dolorum vero!
                </p>
                <a href="#">Mai multe </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="footer">
        <?php include("Footer.html") ?>
      </div>
    </div>
    <script src="views/javascript/navBar.js"></script>
    <script src="views/javascript/pressedfilterButon.js"></script>
  </body>
</html>
