<!DOCTYPE html>

<html lang="ro">
  <head>
    <meta charset="UTF-8" />
    <meta name="description" content="Menagerie on WEB" />
    <meta
      name="keywords"
      content="Menagerie on Web, MeoW, ZOO, zoo, TW proiect, 2B2 "
    />
    <meta name="author" content="Ivan Remus" />
    <meta name="author" content="Lucaci Alexandru-Constantin" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Menagerie on Web</title>

    <link rel="icon" href="views/images/logoBlack.jpg" />
    <link rel="stylesheet" href="views/styles/styleSearch.css" />
    <link rel="stylesheet" href="views/styles/filterlist.css" />
    <link rel="stylesheet" href="views/styles/styleNavBar.css" />
    <link rel="stylesheet" href="views/styles/styleAnimals.css" />
    <link rel="stylesheet" href="views/styles/styleFooter.css" />
    <link rel="stylesheet" type="text/css" href="views/styles/stylefooter2.css" />
    
    <script src="views/javaScript/AnimalsPageButtons.js"></script>
  </head>

  <body>
    <div class="gridBody">
      <div class="content">
        <?php include("NavBar.phtml") ?>
      </div>
      
      <div class="main">
        <div class="filterBar">
          <?php include("CriteriaSearchForm.php"); ?>
        </div>


        <!--If there are results,show the buttons -->
        <?php 
          if(isset($_SESSION['search_results'])&&!empty($_SESSION['search_results'])){

            echo "<div>";
              echo "<form action=\"index.php\" method=\"post\">";
                  echo "<input type=\"hidden\" name=\"load\" value=\"Animals/download\" />";
                  echo "<input type=\"hidden\" name=\"file_format\" value=\"xml\" />";
                  echo "<input type=\"hidden\" name=\"sent_by_session\" value=\"true\" />";
                  echo "<input type=\"submit\" value=\"Descarca rezultate ca XML\" class=\"filtbutt\" />";
              echo "</form>";
            echo "</div>";

            echo "<div>";
              echo "<form action=\"index.php\" method=\"post\">";
                echo "<input type=\"hidden\" name=\"load\" value=\"Animals/download\" />";
                echo "<input type=\"hidden\" name=\"file_format\" value=\"json\" />";
                echo "<input type=\"hidden\" name=\"sent_by_session\" value=\"true\" />";
                echo "<input type=\"submit\" value=\"Descarca rezultate ca JSON\" class=\"filtbutt\" />";
              echo "</form>";
            echo "</div>";

            echo "<div>";
              echo "<button onclick=\"startSelection()\" class=\"filtbutt\">Marcheaza animale</button>";
            echo "</div>";

            echo "<div>";
              echo "<button onclick=\"downloadMarkedAnimals('xml')\" class=\"filtbutt\" >Descarca animale selectate ca XML</button>";
            echo "</div>";

            echo "<div>";
              echo "<button onclick=\"downloadMarkedAnimals('json')\" class=\"filtbutt\">Descarca animale selectate ca JSON</button>";
            echo "</div>";

            if(isset($_SESSION['loggedIn'])&&!empty($_SESSION['loggedIn'])&&$_SESSION['loggedIn']==1&&isset($_SESSION['username'])&&!empty($_SESSION['username'])){
              $username=$_SESSION['username'];
              echo "<div>";
                echo "<button onclick=\"saveMarkedAnimals('$username')\" class=\"filtbutt\" >Salveaza animale selectate</button>";
              echo "</div>";
            }
          }
        ?>

        <div class="itemsContent">
          <div class ="rightplace">
        <?php include("ResultsPage.php"); ?>
        </div> 
      </div>    
      </div>
      <div class="footer">
        <?php include("Footer.html") ?>
      </div>
    </div>
    <script src="views/javascript/navBar.js"></script>
    <script src="views/javascript/pressedfilterButon.js"></script>
  </body>
</html>
