<!DOCTYPE html>

<html lang="ro">
  <head>
    <meta charset="UTF-8" />
    <meta name="description" content="Menagerie on WEB" />
    <meta
      name="keywords"
      content="Menagerie on Web, MeoW, ZOO, zoo, TW proiect, 2B2 "
    />
    <meta name="author" content="Ivan Remus" />
    <meta name="author" content="Lucaci Alexandru-Constantin" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Menagerie on Web</title>

    <link rel="icon" href="views/images/logoBlack.jpg" />
    <link rel="stylesheet" href="views/styles/styleSearch.css" />
    <link rel="stylesheet" href="views/styles/styleNavBar.css" />
    <link rel="stylesheet" href="views/styles/styleAnimals.css" />
    <link rel="stylesheet" href="views/styles/filterlist.css" />
    <link rel="stylesheet" href="views/styles/styleFooter.css" />
    <link rel="stylesheet" type="text/css" href="views/styles/stylefooter2.css" />
  </head>

  <body>
    <div class="gridBody">
      <div class="content">
        <?php include("NavBar.phtml") ?>
      </div>

      <div class="main">
        <div class="filterBar">
          <?php include("CriteriaSearchForm.php"); ?>
        </div>

        <?php include("ResultsPage.php"); ?>
      
      </div>
      <div class="footer">
        <?php include("Footer.html") ?>
      </div>
    </div>
    <script src="views/javascript/navBar.js"></script>
    <script src="views/javascript/pressedfilterButon.js"></script>
  </body>
</html>
