<!DOCTYPE html>
<html lang="ro">
  <head>
    <meta charset="UTF-8" />
    <meta name="description" content="Menagerie on WEB contact information" />
    <meta name="author" content="Ivan Remus" />
    <meta name="author" content="Lucaci Alexandru-Constantin" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Contact Us</title>

    <link rel="icon" href="views/images/logoBlack.jpg" />
   
    <!-- <link rel="stylesheet" href="views/styles/styleNavBar.css" /> -->
  
    <link rel="stylesheet" href="views/styles/styleFooter.css" />
    <link rel="stylesheet" href="views/styles/styleContactPage.css" />
    <link rel="stylesheet" type="text/css" href="views/styles/stylefooter2.css" />
    <link rel="stylesheet" href="views/styles/styleNavBar.css" />
    <link rel="stylesheet" href="views/styles/styleSearch.css" />
  </head>

  <body>
    <div class="content">
      <?php include("NavBar.phtml") ?>
    </div>

    <!-- <br> -->

    <div class="container">
        <div class="row">
            <h1>Contact</h1>
        </div>
        <div class="row">
            <h4 style="text-align:center">Ne-am bucura să te auzim!</h4>
        </div>

            <div class="row input-container">
                <div class="col-xs-12">
                  <div class="styled-input wide">
                    <input type="text" required />
                    <label>Nume</label> 
                  </div>
                </div>
                <div class="col-md-6 col-sm-12">
                  <div class="styled-input">
                    <input type="text" required />
                    <label>Email</label> 
                  </div>
                </div>
                <div class="col-md-6 col-sm-12">
                  <div class="styled-input" style="float:right;">
                    <input type="text" required />
                    <label>Număr de telefon</label> 
                  </div>
                </div>
                <div class="col-xs-12">
                  <div class="styled-input wide">
                    <textarea required></textarea>
                    <label>Mesaj</label>
                  </div>
                </div>
                <div class="col-xs-12">
                  <div class="btn-lrg submit-btn">Trimite mesajul</div>
                </div>
            </div>
    </div>

    <script src="views/javascript/navBar.js"></script>
  </body>
</html>
