<!DOCTYPE html>
<html lang="ro">
  <head>
    <meta charset="UTF-8" />
    <meta name="description" content="Menagerie on WEB contact information" />
    <meta name="author" content="Ivan Remus" />
    <meta name="author" content="Lucaci Alexandru-Constantin" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Contact Us</title>

    <link rel="icon" href="views/images/logoBlack.jpg" />
    <link rel="stylesheet" href="views/styles/styleSearch.css" />
    <link rel="stylesheet" href="views/styles/styleNavBar.css" />
    <link rel="stylesheet" href="views/styles/stylelogin.css" />
    <link rel="stylesheet" href="views/styles/styleFooter.css" />
    <link rel="stylesheet" href="views/styles/styleContactPage.css" />
    <link rel="stylesheet" type="text/css" href="views/styles/stylefooter2.css" />
  </head>

  <body>
    <div class="content">
      <?php include("NavBar.phtml") ?>
    </div>

    <!-- <br> -->

    <div class="contact-image-container">
      <img src="views/images/contactUs.jpg" alt="contact us image" />
    </div>

    <!-- <br /> -->

    <div class="contact-form-container">
      <div class="contact-title">
        <p>Contacteaza-ne</p>
      </div>

      <form class="contact-form-grid">
        <label for="fname">Nume</label>
        <input
          type="text"
          id="fname"
          name="firstname"
          placeholder="Numele de familie..."
        />

        <label for="lname">Prenume</label>
        <input
          type="text"
          id="lname"
          name="lastname"
          placeholder="Prenumele..."
        />

        <label for="email">Email</label>
        <input
          type="email"
          id="email"
          name="emailaddress"
          placeholder="Adresa ta de email..."
        />

        <label for="phone">Numar de telefon</label>
        <input
          type="tel"
          id="phone"
          name="phonenumber"
          placeholder="Numarul tau de telefon..."
          pattern="[0-9]{10}"
        />

        <label for="subject">Subiect</label>
        <textarea
          id="subject"
          name="subject"
          placeholder="Scrie ceva..."
        ></textarea>

        <input type="submit" value="Send" />
      </form>
    </div>

    <!-- <br /> -->

    <?php include("Footer.html") ?>   

    <script src="views/javascript/navBar.js"></script>
  </body>
</html>
