<!DOCTYPE html>
<html lang="ro">
  <head>
    <meta charset="UTF-8" />
    <meta name="description" content="Menagerie on WEB help" />
    <meta name="author" content="Ivan Remus" />
    <meta name="author" content="Lucaci Alexandru-Constantin" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>How can we help</title>

    <link rel="icon" href="views/images/logoBlack.jpg" />
    <link rel="stylesheet" href="views/styles/styleNavBar.css" />
    <link rel="stylesheet" href="views/styles/styleSearch.css" />
    <link rel="stylesheet" href="views/styles/styleFooter.css" />
    <link rel="stylesheet" href="views/styles/styleHelpPage.css" />
    <link rel="stylesheet" type="text/css" href="views/styles/stylefooter2.css" />
  </head>

  <body>
    <div class="content">
      <?php include("NavBar.phtml") ?>
    </div>

    <div class="help-container">
      <div class="help-title">
        <p>Cum te putem ajuta?</p>
      </div>
    </div>

    <div class="help-questions-grid">
      <div class="help-questions-title">
        <p>Intrebari frecvente</p>
      </div>

      <br />

      <button class="help-question-button">
        &#9654; Lorem ipsum dolor sit amet.
      </button>
      <div class="help-answer">
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit,
          molestiae eius laborum modi quidem mollitia!
        </p>
      </div>

      <button class="help-question-button">
        &#9654; Lorem ipsum dolor sit amet.
      </button>
      <div class="help-answer">
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident
          nesciunt tempora doloremque ab cupiditate! Quasi itaque sit quisquam
          aliquam illo obcaecati molestias alias, praesentium neque nihil
          deserunt odit earum maiores, mollitia placeat tempore accusantium
          dolor voluptatibus ducimus! Corporis, illo exercitationem.
        </p>
      </div>

      <button class="help-question-button">
        &#9654; Lorem ipsum dolor sit amet.
      </button>
      <div class="help-answer">
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit,
          molestiae eius laborum modi quidem mollitia!
        </p>
      </div>

      <button class="help-question-button">
        &#9654; Lorem ipsum dolor sit amet.
      </button>
      <div class="help-answer">
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit,
          molestiae eius laborum modi quidem mollitia!
        </p>
      </div>

      <button class="help-question-button">
        &#9654; Lorem ipsum dolor sit amet.
      </button>
      <div class="help-answer">
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit,
          molestiae eius laborum modi quidem mollitia!
        </p>
      </div>
    </div>

    <?php include("Footer.html") ?>

    <script src="views/javascript/HelpPageAnswer.js"></script>
    <script src="views/javascript/navBar.js"></script>
  </body>
</html>
