<!DOCTYPE html>
<html lang="ro">
  <head>
    <meta charset="UTF-8" />
    <meta name="description" content="Menagerie on WEB help" />
    <meta name="author" content="Ivan Remus" />
    <meta name="author" content="Lucaci Alexandru-Constantin" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>How can we help</title>

    <link rel="icon" href="views/images/logoBlack.jpg" />
    <link rel="stylesheet" href="views/styles/styleNavBar.css" />
    <link rel="stylesheet" href="views/styles/styleSearch.css" />
    <link rel="stylesheet" href="views/styles/styleFooter.css" />
    <link rel="stylesheet" href="views/styles/styleHelpPage.css" />
  </head>

  <body>
    <div class="content">
      <div class="nav-containter">
        <nav class="navbar">
          <div class="search">
            <div class="searchBar">
              <input
                class="search-txt"
                type="text"
                name="searchField"
                placeholder="Type to search"
              />
              <a class="search-bth" href="#"></a>
              <img
                src="views/icons/searchBar.svg"
                alt="SearchBarBtn"
                width="25"
                height="25"
              />
            </div>
          </div>
          <div class="menu-togle" id="mobile-menu">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
          </div>
          <ul class="nav-menu">
            <li><a href="http://localhost/ProjectMeoW/TW/index.php" class="nav-links">Acasa</a></li>
            <li><a href="http://localhost/ProjectMeoW/TW/index.php?load=Animals/show" class="nav-links">Animale</a></li>
            <li><a href="http://localhost/ProjectMeoW/TW/index.php?load=About/show" class="nav-links">Despre</a></li>
            <li><a href="http://localhost/ProjectMeoW/TW/index.php?load=Help/show" class="nav-links">Ajutor</a></li>
            <li>
              <a href="http://localhost/ProjectMeoW/TW/index.php?load=Contact/show" class="nav-links nav-links-btn">Contact</a>
            </li>
            <li>
              <a href="http://localhost/ProjectMeoW/TW/index.php?load=Login/show" class="nav-links nav-links-btn"
                >Autentificare</a
              >
            </li>

            <!-- <li><a href="" class="nav-links ">Login</a></li> -->
          </ul>
        </nav>
      </div>
    </div>

    <div class="help-container">
      <div class="help-title">
        <p>Cum te putem ajuta?</p>
      </div>
    </div>

    <div class="help-questions-grid">
      <div class="help-questions-title">
        <p>Intrebari frecvente</p>
      </div>

      <br />

      <button class="help-question-button">
        &#9654; Lorem ipsum dolor sit amet.
      </button>
      <div class="help-answer">
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit,
          molestiae eius laborum modi quidem mollitia!
        </p>
      </div>

      <button class="help-question-button">
        &#9654; Lorem ipsum dolor sit amet.
      </button>
      <div class="help-answer">
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident
          nesciunt tempora doloremque ab cupiditate! Quasi itaque sit quisquam
          aliquam illo obcaecati molestias alias, praesentium neque nihil
          deserunt odit earum maiores, mollitia placeat tempore accusantium
          dolor voluptatibus ducimus! Corporis, illo exercitationem.
        </p>
      </div>

      <button class="help-question-button">
        &#9654; Lorem ipsum dolor sit amet.
      </button>
      <div class="help-answer">
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit,
          molestiae eius laborum modi quidem mollitia!
        </p>
      </div>

      <button class="help-question-button">
        &#9654; Lorem ipsum dolor sit amet.
      </button>
      <div class="help-answer">
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit,
          molestiae eius laborum modi quidem mollitia!
        </p>
      </div>

      <button class="help-question-button">
        &#9654; Lorem ipsum dolor sit amet.
      </button>
      <div class="help-answer">
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit,
          molestiae eius laborum modi quidem mollitia!
        </p>
      </div>
    </div>

    <div class="contact-information-grid">
      <div class="contact-title">
        <p>Informatii contact</p>
      </div>

      <div class="contact-details-grid">
        <div class="contact-detail">
          <p>
            <strong>Adresa</strong> : Lorem ipsum dolor sit amet consectetur
            adipisicing elit. Nesciunt, saepe.
          </p>
        </div>

        <div class="contact-detail">
          <p>
            <strong>Administrator</strong> : Lorem ipsum dolor sit amet
            consectetur adipisicing elit. Rem, veniam.
          </p>
        </div>

        <div class="contact-detail">
          <p>
            <strong>Numar de telefon</strong> : Lorem, ipsum dolor sit amet
            consectetur adipisicing elit. Commodi, unde.
          </p>
        </div>

        <div class="contact-detail">
          <p>
            <strong>Facebook</strong> : Lorem ipsum dolor sit amet, consectetur
            adipisicing elit. Dolorem, nihil!
          </p>
        </div>

        <div class="contact-detail">
          <p>
            <strong>Email</strong> : Lorem ipsum dolor sit amet consectetur,
            adipisicing elit. Omnis, voluptatibus!
          </p>
        </div>
      </div>
    </div>

    <script src="views/javascript/HelpPageAnswer.js"></script>
    <script src="views/javascript/navBar.js"></script>
  </body>
</html>
