<!DOCTYPE html>

<html lang="ro">
  <head>
    <meta charset="UTF-8" />
    <meta name="description" content="Menagerie on WEB" />
    <meta
      name="keywords"
      content="Menagerie on Web, MeoW, ZOO, zoo, TW proiect, 2B2 "
    />
    <meta name="author" content="Ivan Remus" />
    <meta name="author" content="Lucaci Alexandru-Constantin" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Menagerie on Web</title>

    <link rel="icon" href="views/images/logoBlack.jpg" />
    <link rel="stylesheet" type="text/css" href="views/styles/languageSelector.css" />
    <link rel="stylesheet" type="text/css" href="views/styles/styleHeader.css" />
    <link rel="stylesheet" type="text/css" href="views/styles/style.css" />
    <link rel="stylesheet" type="text/css" href="views/styles/styleSearch.css" />
    <link rel="stylesheet" type="text/css" href="views/styles/styleIndex.css" />
    <link rel="stylesheet" type="text/css" href="views/styles/styleFooter.css" />
    <!-- <link rel="stylesheet" href="styles\styleNav.css" /> -->

    <link rel="stylesheet" type="text/css" href="views/styles/styleMainPage.css" />
    <link rel="stylesheet" type="text/css" href="views/styles/styleNavBar.css" />
    <link rel="stylesheet" type="text/css" href="views/styles/stylefooter2.css" />
  </head>

  <body>
    <!-- <img src="icons\searchBar.svg" alt="Search bar" /> -->
    <div class="gridBody">
      <div class="title">
        <div class="header">
          <div class="sides">
            <!-- <img src="pictures\logoBlack.jpg" alt="Managerie on Web" /> -->
            <a href="#" class="logo">Managerie on Web</a>
          </div>
          <div class="sides">
            <!-- <a href="#" class="menu"> </a> -->
            <div class="login">
              <div class="limba">
                <!-- language -->
                <div class="lang-menu">
                  <div class="selected-lang">Română</div>
                  <ul>
                    <li>
                      <a href="#" class="romanaLanguage">Română</a>
                    </li>
                    <li>
                      <a href="#" class="englishLanguage"><del>English</del></a>
                    </li>
                    <li>
                      <a href="#" class="frenchLanguage"><del>French</del></a>
                    </li>
                  </ul>
                </div>
              </div>
              <!-- <div class="conectare">login</div> -->
            </div>
          </div>

          <div class="info">
            <h4>
              <a href="https://profs.info.uaic.ro/~vcosmin/proiectetw"
                >Despre</a
              >
            </h4>
            <h1>MeoW (Menagerie on Web)</h1>
            <div class="meta">
              <a href="https://facebook.com" target="_blank" class="author"></a
              ><br />
              Facut de
              <a
                href="https://profs.info.uaic.ro/~orar/participanti/orar_I2B2.html"
                target="_blank"
                >Ivan Remus si Lucaci Alexandru
              </a>
              in Aprilie 2022
            </div>
          </div>
        </div>
      </div>

      <div class="content">
        <?php include("NavBar.phtml") ?>
      </div>

      <div class="Main">
        <div class="slideshow-container">
          <div class="mySlide fade">
            <div class="slideshow-number-text">1 / 3</div>
            <img src="views/images/img1.jpg" alt="lion image" />
          </div>

          <div class="mySlide fade">
            <div class="slideshow-number-text">2 / 3</div>
            <img src="views/images/img2.jpg" alt="girrafe image" />
          </div>

          <div class="mySlide fade">
            <div class="slideshow-number-text">3 / 3</div>
            <img src="views/images/img3.jpg" alt="tiger image" />
          </div>

          <a class="slideshow-previous-button" onclick="changeSlides(-1)"
            >&#10094;</a
          >
          <a class="slideshow-next-button" onclick="changeSlides(1)"
            >&#10095;</a
          >
        </div>
        <br />

        <div class="slideshow-dots-container">
          <span class="dot" onclick="setCurrentSlides(1)"></span>
          <span class="dot" onclick="setCurrentSlides(2)"></span>
          <span class="dot" onclick="setCurrentSlides(3)"></span>
        </div>
        <br />

        <div class="welcome-grid">
          <div>
            <p>&#9654; A.A. Milne</p>
          </div>
          <div>
            <p>
              „Mulţi oameni vorbesc animalelor. Puţini le ascultă. Asta este problema.”
            </p>
          </div>

          <div>
            <p>&#9654; Irene M. Pepperberg</p>
          </div>

          <div>
            <p>
            "Este cât se poate de clar că animalele ştiu mai mult decât ne gândim, şi gândesc cu mult mai mult decât ştim."
            </p>
          </div>

          <div>
            <p>&#9654; Immanuel Kant</p>
          </div>

          <div>
            <p>
            "Cel care este crud cu animalele devine, de asemeni, crud în interacţiunea sa cu oamenii. Putem judecă inima cuiva după felul cum se poartă cu animalele."
            </p>
          </div>
        </div>
      </div>

      <div class="footer">
        <?php include("Footer.html") ?>
      </div>

    </div>

    <script src="views/javascript/navBar.js"></script>
    <script src="views/javascript/MainPageSlideshow.js"></script>
  </body>
</html>
