<!DOCTYPE html>
<html lang="ro">
  <head>
    <meta charset="UTF-8" />
    <meta name="description" content="Menagerie on WEB contact information" />
    <meta name="author" content="Ivan Remus" />
    <meta name="author" content="Lucaci Alexandru-Constantin" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Importa animale</title>

    <link rel="icon" href="views/images/logoBlack.jpg" />
   

    
    <link rel="stylesheet" href="views/styles/styleNavBar.css" />
    <link rel="stylesheet" href="views/styles/styleSearch.css" />
    <link rel="stylesheet" href="views/styles/styleContactPage.css" />
    <link rel="stylesheet" href="views/styles/styleImport.css" />
  </head>

  <body>
    <div class="content">
      <?php include("NavBar.phtml") ?>
    </div> 
     <br>

    <div class="container">
        <div class="row">
            <h1>Inserează informații despre un animal în baza de date introducând valorile respective pentru fiecare câmp.
            </h1>
        </div>
        <div class="row">
            <h4 style="text-align:center"> Fiecare câmp are o limita de caractere care poate fi introdusa(maxim 4000).</h4>
        </div>

        <form action="index.php" method="post">
          <input type="hidden" name="load" value="Import/update">
          <input type="hidden" name="function" value="insert_animal_info">
          <input type="hidden" name="input_option" value="direct">

            <div class="row input-container">


                <div class="col-md-6 col-sm-12">
                  <div class="styled-input">
                    <input type="text" name="DENUMIRE_POPULARA"  required="" />
                    <label>DENUMIRE_POPULARA</label> 
                  </div>
                </div>
                <div class="col-md-6 col-sm-12">
                  <div class="styled-input" style="float:right;">
                    <input type="text" name="DENUMIRE_STINTIFICA" required="" />
                    <label>DENUMIRE_STINTIFICA</label> 
                  </div>
                </div>
                <div class="col-xs-12">
                  <div class="styled-input wide">
                    <input type="text" name="MINI_DESCRIERE" maxlength="500" required=""/>
                    <label>MINI_DESCRIERE</label> 
                  </div>
                </div>

                

                <div class="col-xs-12">
                  <div class="styled-input wide">
                    <textarea name="ETIMOLOGIE" maxlength="4000"></textarea>
                    <label>ETIMOLOGIE</label>
                  </div>
                </div>
                

                <div class="col-md-6 col-sm-12">
                  <div class="styled-input">
                    <input type="text" name="ORIGINE" maxlength="20" />
                    <label>ORIGINE</label> 
                  </div>
                </div>
                <div class="col-md-6 col-sm-12">
                  <div class="styled-input" style="float:right;">
                    <input type="text" name="CLASA" maxlength="20" />
                    <label>CLASA</label> 
                  </div>
                </div>
                <div class="col-xs-12">
                  <div class="styled-input wide">
                    <input type="text" name="HABITAT" maxlength="40"/>
                    <label>HABITAT</label> 
                  </div>
                </div>  
                <div class="col-xs-12">
                  <div class="styled-input wide">
                    <input type="text" name="STARE_DE_CONSERVARE" maxlength="40"/>
                    <label>STARE_DE_CONSERVARE</label> 
                  </div>
                </div>             
                <div class="col-md-6 col-sm-12">
                  <div class="styled-input">
                    <input type="text" name="INVAZIVA" maxlength="20" />
                    <label>INVAZIVA</label> 
                  </div>
                </div>
                <div class="col-md-6 col-sm-12">
                  <div class="styled-input" style="float:right;">
                    <input type="text" name="REGIM_ALIMENTAR" maxlength="15"/>
                    <label>REGIM_ALIMENTAR</label> 
                  </div>
                </div>
                <div class="col-xs-12">
                  <div class="styled-input wide">
                    <textarea name="DIETA" maxlength="1300"></textarea>
                    <label>DIETA</label>
                  </div>
                </div>

                <div class="col-xs-12">
                  <div class="styled-input wide">
                    <input type="text" name="MOD_DE_INMULTIRE" maxlength="30"/>
                    <label>MOD_DE_INMULTIRE</label> 
                  </div>
                </div>

                <div class="col-xs-12">
                  <div class="styled-input wide">
                    <textarea name="REPRODUCERE" maxlength="1300"></textarea>
                    <label>REPRODUCERE</label>
                  </div>
                </div>

                <div class="col-xs-12">
                  <div class="styled-input wide">
                    <textarea name="DEZVOLTARE" maxlength="4000"></textarea>
                    <label>DEZVOLTARE</label>
                  </div>
                </div>

                <div class="col-xs-12">
                  <div class="styled-input wide">
                    <textarea name="VIATA" maxlength="4000"></textarea>
                    <label>VIATA</label>
                  </div>
                </div>

                <div class="col-xs-12">
                  <div class="styled-input wide">
                    <textarea name="ISTORIE" maxlength="4000"></textarea>
                    <label>ISTORIE</label>
                  </div>
                </div>

                <div class="col-xs-12">
                  <div class="styled-input wide">
                    <textarea name="DUSMANI_NATURALI" maxlength="4000"></textarea>
                    <label>DUSMANI_NATURALI</label>
                  </div>
                </div>
                <div class="col-xs-12">
                  <input type="submit">
                </div>
            </div>
          </form>

          <div class="row">
            <h1>Import folosing XML/JSON.
            </h1>
        </div>
        <div class="row">
            <h4 style="text-align:center">            
              Incarca informatii despre animale in baza de date incarcand un fisier XML/JSON.
              Dimensiunea maxima a unui fisier permisa este de 1GB.
              Daca exista un camp in fisier care nu corespunde cu numele unei coloane din baza de date,acesta va fi ignorat.
              Trebuie sa respecte structura urmatoare:.</h4>
        </div>
        <pre>
          animale{
              animal{
                  nume_camp1=valoare,
                  nume_camp2=valoare
                  ...
              }
              animal{
                  nume
              }
          }
        </pre>
    </h4>

      <form action="index.php" method="post" enctype="multipart/form-data">
        <input type="hidden" name="load" value="Import/update">
        <input type="hidden" name="function" value="insert_animal_info">
        <input type="hidden" name="input_option" value="file">
        
        <input type="file" name="file" />
        
        <input type="submit">
      </form>
    </div>

    <?php 
      if(is_string($data)&&!empty($data)){
        echo "<h4>Mesaj:$data</h4>";
      }
    ?>

    <script src="views/javascript/navBar.js"></script>
  </body>
</html>
