<!DOCTYPE html>

<html lang="ro">
  <head>
    <meta charset="UTF-8" />
    <meta name="description" content="Menagerie on WEB" />
    <meta
      name="keywords"
      content="Menagerie on Web, MeoW, ZOO, zoo, TW proiect, 2B2 "
    />
    <meta name="author" content="Ivan Remus" />
    <meta name="author" content="Lucaci Alexandru-Constantin" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Menagerie on Web</title>

    <link rel="icon" href="views/images/logoBlack.jpg" />
    <!-- <link rel="stylesheet" href="styles/languageSelector.css" /> -->
    <!-- <link rel="stylesheet" href="styles/styleHeader.css" /> -->
    <!-- <link rel="stylesheet" href="styles/style.css" /> -->
    <link rel="stylesheet" href="views/styles/styleSearch.css" />
    <!-- <link rel="stylesheet" href="styles/styleIndex.css" /> -->
    <!-- <link rel="stylesheet" href="styles\styleNav.css" /> -->

    <!-- <link rel="stylesheet" href="styles/styleMainPage.css" /> -->
    
    <link rel="stylesheet" href="views/styles/styleLogin.css" />
    <link rel="stylesheet" href="views/styles/styleNavBar.css" />
    <link rel="stylesheet" type="text/css" href="views/styles/stylefooter2.css" />
   
  </head>

  <body>
    <div class="content">
      <?php include("NavBar.phtml") ?>
    </div>
    <div class="log">
      <div class="main">  	
        <input class="loginPageInput" type="checkbox" id="chk" aria-hidden="true">
        <div class="signup">
          <form action="index.php" method="post">
            <input class="loginPageInput" type="hidden" name="load" value="Login/update" />
            <input class="loginPageInput" type="hidden" name="function" value="register" />

            <label for="chk" aria-hidden="true">Inregistrare</label>
            <input class="loginPageInput" type="text" name="username" placeholder="Nume" required="" />
            <input class="loginPageInput" type="password" name="password" placeholder="Parola" required="" />
            <input class="loginPageInput" type="email" name="email" placeholder="Email" />
            <input class="loginPageInput" type="tel" name="telephone" placeholder="Numar de telefon" />
            <button>Inregistrare</button>
          </form>
        </div>

        <div class="login">
          <form action="index.php" method="post">
            <input class="loginPageInput" type="hidden" name="load" value="Login/update" />
            <input class="loginPageInput" type="hidden" name="function" value="login" />

            <label for="chk" aria-hidden="true">Autentificare</label>
            <input class="loginPageInput" type="text" name="username" placeholder="Nume" required="" />
            <input class="loginPageInput" type="password" name="password" placeholder="Parola" required="">
            <button>Autentificare</button>
          </form>
        </div>
	    </div>
    </div>

    <?php 
      if(isset($data)&&!empty($data)){
        echo "<p style=\"color:white\">$data</p>";
      }
    ?>
    
    <div class="footer">
      <?php include("Footer.html") ?>
    </div>


    
    

    <script src="views/javascript/navBar.js"></script>
  </body>
</html>
