<!DOCTYPE html>

<html lang="ro">
  <head>
    <meta charset="UTF-8" />
    <meta name="description" content="Menagerie on WEB" />
    <meta
      name="keywords"
      content="Menagerie on Web, MeoW, ZOO, zoo, TW proiect, 2B2 "
    />
    <meta name="author" content="Ivan Remus" />
    <meta name="author" content="Lucaci Alexandru-Constantin" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Menagerie on Web</title>

    <link rel="icon" href="views/images/logoBlack.jpg" />
    <!-- <link rel="stylesheet" href="styles/languageSelector.css" /> -->
    <!-- <link rel="stylesheet" href="styles/styleHeader.css" /> -->
    <!-- <link rel="stylesheet" href="styles/style.css" /> -->
    <link rel="stylesheet" href="views/styles/styleSearch.css" />
    <!-- <link rel="stylesheet" href="styles/styleIndex.css" /> -->
    <link rel="stylesheet" href="views/styles/styleFooter.css" />
    <!-- <link rel="stylesheet" href="styles\styleNav.css" /> -->

    <!-- <link rel="stylesheet" href="styles/styleMainPage.css" /> -->
    <link rel="stylesheet" href="views/styles/styleNavBar.css" />
    <link rel="stylesheet" href="views/styles/stylelogin.css" />
    <link rel="stylesheet" type="text/css" href="views/styles/stylefooter2.css" />
  </head>

  <body>
    <div class="content">
      <?php include("NavBar.phtml") ?>
    </div>
    <div class="log">
      <form action="index.php" method="post">
        <div class="imgcontainer">
          <img src="views/images/logoBlack.jpg" alt="Logo" class="avatar" />
        </div>

        <div class="container">
            <input type="hidden" name="load" value="Login/account_command" />
            
            <input type="hidden" name="function" value="login" />
            
            <label for="username"><b>Nume de utilizator:</b></label>
            <input
              type="text"
              placeholder="Introdu numele de utilizator"
              name="username"
              required
            />

            <label for="password"><b>Parolă</b></label>
            <input
              type="password"
              placeholder="Introdu parola"
              name="password"
              required
            />

            <button type="submit">Loghează-te</button>
            <label>
              <input type="checkbox" checked="checked" name="remember" /> Ține-mă
              minte
            </label>
          </form>
        </div>

        <div class="container" style="background-color: #212329">
          <button type="button" class="cancelbtn">Cancel</button>
          <span class="psw">Ai uitat <a href="#">parola?</a></span>
        </div>
      </form>
    </div>
    <div class="footer">
      <?php include("Footer.html") ?>
    </div>

    <?php
                
      echo "<pre>";
      print_r($_SESSION);
      echo "</pre>";

      $loggedIn=null;
      $info=null;

      if(isset($_SESSION['loggedIn'])){
          $loggedIn=$_SESSION['loggedIn'];

          if($loggedIn==0){
              $info="Not logged into any account";
          }
          else{
              $info="Logged in.\nUsername:".$_SESSION['username'];
          }

      }else{
          $info="Unknown status";
      }
      
      echo "<p>$info</p>";
    ?>

    <?php
      echo "<pre>";
      print_r($data);
      echo "</pre>";
    ?>
    
    

    <script src="views/javascript/navBar.js"></script>
  </body>
</html>
