<!DOCTYPE html>

<html lang="ro">
  <head>
    <meta charset="UTF-8" />
    <meta name="description" content="Menagerie on WEB" />
    <meta
      name="keywords"
      content="Menagerie on Web, MeoW, ZOO, zoo, TW proiect, 2B2 "
    />
    <meta name="author" content="Ivan Remus" />
    <meta name="author" content="Lucaci Alexandru-Constantin" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Menagerie on Web</title>

    <link rel="icon" href="views/images/logoBlack.jpg" />
    <!-- <link rel="stylesheet" href="styles/languageSelector.css" /> -->
    <!-- <link rel="stylesheet" href="styles/styleHeader.css" /> -->
    <!-- <link rel="stylesheet" href="styles/style.css" /> -->
    <link rel="stylesheet" href="views/styles/styleSearch.css" />
    <!-- <link rel="stylesheet" href="styles/styleIndex.css" /> -->
    <!-- <link rel="stylesheet" href="styles\styleNav.css" /> -->

    <!-- <link rel="stylesheet" href="styles/styleMainPage.css" /> -->
    <link rel="stylesheet" href="views/styles/styleNavBar.css" />
    <link rel="stylesheet" href="views/styles/stylelogin.css" />
    <link rel="stylesheet" type="text/css" href="views/styles/stylefooter2.css" />
   
  </head>

  <body>
    <div class="content">
      <?php include("NavBar.phtml") ?>
    </div>
    <div class="log">
      <div class="main">  	
      <input type="checkbox" id="chk" aria-hidden="true">
        <div class="signup">
          <form>
            <label for="chk" aria-hidden="true">Sign up</label>
            <input type="text" name="txt" placeholder="User name" required="">
            <input type="email" name="email" placeholder="Email" required="">
            <input type="password" name="pswd" placeholder="Password" required="">
            <button>Sign up</button>
          </form>
        </div>

        <div class="login">
          <form>
            <label for="chk" aria-hidden="true">Login</label>
            <input type="email" name="email" placeholder="Email" required="">
            <input type="password" name="pswd" placeholder="Password" required="">
            <button>Login</button>
          </form>
        </div>
	  </div>
</div>
    <div class="footer">
      <?php include("Footer.html") ?>
    </div>


    
    

    <script src="views/javascript/navBar.js"></script>
  </body>
</html>
