<script>
    function sugestii(str){
        console.log(str);
        if(str.length==0)
        {
            document.getElementById('output').innerHTML='';
        }
        else{
            // document.getElementById('output').innerHTML=str;
            // AJAX

            var xmlhttp = new XMLHttpRequest();
            xmlhttp.onreadystatechange= function(){
                if(this.readyState==4 && this.status==200){
                    document.getElementById('output').innerHTML = this.responseText;
                    // console.log("yesss");
                }
            }
            xmlhttp.open("GET", "/tw/models/ajax/suggest.php?q="+str,true);
            xmlhttp.send();
        }
    }
</script>


<div class="nav-container">
    <nav class="navbar">
        <div class="search">
            <div class="searchBar">
                <form action="index.php" method="post">
                    <input
                    class="search-txt"
                    type="text"
                    name="text"
                    placeholder="Type to search"
                    onkeyup="sugestii(this.value)"
                    
                    />
                    <input type="hidden" name="load" value="Animals/update" />
                    <input type="hidden" name="function" value="search" />
                    <input type="submit" hidden />
                    <a class="search-bth" href="#"></a>
                    <img
                    src="views/icons/searchBar.svg"
                    alt="SearchBarBtn"
                    width="25"
                    height="25"
                    />
                    <p><span id="output" style="font-weight:bold">a</span></p>
                </form>
            </div>
        </div>
        <div class="menu-togle" id="mobile-menu">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </div>
        <ul class="nav-menu">
            <li><a href="index.php" class="nav-links">Acasa</a></li>
            <li><a href="index.php?load=Animals/show" class="nav-links">Animale</a></li>
            <li><a href="index.php?load=About/show" class="nav-links">Despre</a></li>
            <li><a href="index.php?load=Help/show" class="nav-links">Ajutor</a></li>
            <!-- <li><a href="index.php?load=Import/show" class="nav-links">import</a></li> -->
            <li>
                <a href="index.php?load=Contact/show" class="nav-links nav-links-btn">Contact</a>
            </li>
            <?php 
            // session_start();
                if(isset($_SESSION['login'])&&$_SESSION['login']==1){
                    $username=$_SESSION['name'];

                    echo "<li><a href=\"index.php?load=Settings/show\" class=\"nav-links nav-links-btn \">Nume:$username</a></li>";

                    echo "<li>";
                        echo "<form action=\"index.php\" method=\"post\">";
                            echo "<input type=\"hidden\" name=\"load\" value=\"Login/doRegOrLog\" />";
                            echo "<input type=\"hidden\" name=\"function\" value=\"logout\" />";

                            echo "<input type=\"submit\" value=\"Deconecteaza-te\" class=\"nav-links nav-links-btn \"/>";

                        echo "</form>";
                    echo "</li>";
                }
                else{
                    echo "<li> <a href=\"index.php?load=Login/show\" class=\"nav-links nav-links-btn\">Autentificare</a></li>";
                }
            ?>
            
            <!-- <li><a href="" class="nav-links ">Login</a></li> -->
        </ul>
    </nav>
</div>