<div class="nav-container">
    <nav class="navbar">
        <div class="search">
            <div class="searchBar">
                <form action="index.php" method="post">
                    <input
                    class="search-txt"
                    type="text"
                    name="text"
                    placeholder="Type to search"
                    />
                    <input type="hidden" name="load" value="Animals/show" />
                    <input type="hidden" name="function" value="score_search" />
                    <input type="submit" hidden />
                    <a class="search-bth" href="#"></a>
                    <img
                    src="views/icons/searchBar.svg"
                    alt="SearchBarBtn"
                    width="25"
                    height="25"
                    />
                </form>
            </div>
        </div>
        <div class="menu-togle" id="mobile-menu">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </div>
        <ul class="nav-menu">
            <li><a href="index.php" class="nav-links">Acasa</a></li>
            <li><a href="index.php?load=Animals/show" class="nav-links">Animale</a></li>
            <li><a href="index.php?load=About/show" class="nav-links">Despre</a></li>
            <li><a href="index.php?load=Help/show" class="nav-links">Ajutor</a></li>
            <!-- <li><a href="index.php?load=Import/show" class="nav-links">import</a></li> -->
            <li>
                <a href="index.php?load=Contact/show" class="nav-links nav-links-btn">Contact</a>
            </li>
            <?php 
                if(isset($_SESSION['loggedIn'])&&$_SESSION['loggedIn']==1){
                    $username=$_SESSION['username'];

                    echo "<li><a href=\"index.php?load=Settings/show\" class=\"nav-links nav-links-btn \">Nume:$username</a></li>";

                    echo "<li>";
                        echo "<form action=\"index.php\" method=\"post\">";
                            echo "<input type=\"hidden\" name=\"load\" value=\"Settings/update\" />";
                            echo "<input type=\"hidden\" name=\"function\" value=\"logout\" />";

                            echo "<input type=\"submit\" value=\"Deconecteaza-te\" class=\"nav-links nav-links-btn \"/>";

                        echo "</form>";
                    echo "</li>";
                }
                else{
                    echo "<li> <a href=\"index.php?load=Login/show\" class=\"nav-links nav-links-btn\">Autentificare</a></li>";
                }
            ?>
            
            <!-- <li><a href="" class="nav-links ">Login</a></li> -->
        </ul>
    </nav>
</div>