<div class="nav-containter">
    <nav class="navbar">
        <div class="search">
            <div class="searchBar">
                <input
                class="search-txt"
                type="text"
                name="searchField"
                placeholder="Type to search"
                />
                <a class="search-bth" href="#"></a>
                <img
                src="views/icons/searchBar.svg"
                alt="SearchBarBtn"
                width="25"
                height="25"
                />
            </div>
        </div>
        <div class="menu-togle" id="mobile-menu">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </div>
        <ul class="nav-menu">
            <li><a href="index.php" class="nav-links">Acasa</a></li>
            <li><a href="index.php?load=Animals/show" class="nav-links">Animale</a></li>
            <li><a href="index.php?load=About/show" class="nav-links">Despre</a></li>
            <li><a href="index.php?load=Help/show" class="nav-links">Ajutor</a></li>
            <li>
                <a href="index.php?load=Contact/show" class="nav-links nav-links-btn">Contact</a>
            </li>
            <li>
                <a href="index.php?load=Login/show" class="nav-links nav-links-btn"
                >Autentificare</a
                >
            </li>
            <!-- <li><a href="" class="nav-links ">Login</a></li> -->
        </ul>
    </nav>
</div>