<!DOCTYPE html>
<html lang="ro">
    <head>
        <title>Salvari</title>
        <link rel="stylesheet" type="text/css" href="views/styles/styleAnimals.css" />
        <link rel="stylesheet" type="text/css" href="views/styles/styleNavBar.css" />
        <link rel="stylesheet" type="text/css" href="views/styles/stylefooter2.css" />
        <link rel="stylesheet" type="text/css" href="views/styles/styleSearch.css" />
        
        <link rel="stylesheet" type="text/css" href="views/styles/styleSettings.css" />
        <!-- <link rel="stylesheet" href="views/styles/buttons.css" /> -->
        <link rel="stylesheet" type="text/css" href="views/styles/styleSavedAnimals.css" />
    </head>
    <body>

    <?php

        include("NavBar.phtml"); 
        echo "
        <div class=\"wrapper\"><div class=\"left\">
          <h4>$username</h4>";
       

        echo "<h4> <div class =\"links\">";
        include("AccountNavBar.phtml");
        echo "</div></h4></div>";
        
    ?>;
    
    <!-- <h2>Animale salvate</h2> -->

    <?php 
        // $username=$data['user_info']['NUME_UTILIZATOR'];
        echo "<div class=\"right\">
        <div class=\"info\">
          <h3>Information</h3>
        </div>";
        
        include("SavedAnimalsPage.phtml");

        echo "</div>";

        if(isset($_SESSION["saved_animals"])&&!empty(($_SESSION["saved_animals"]))){
            echo "<div>";
                echo "<form action=\"index.php\" method=\"post\">";
                    echo "<input type=\"hidden\" name=\"load\" value=\"Savings/download\" />";
                    echo "<input type=\"hidden\" name=\"file_format\" value=\"xml\" />";
                    echo "<input type=\"submit\" value=\"Descarca salvari ca XML\" />";
                echo "</form>";
            echo "</div>";

            echo "<div>";
                echo "<form action=\"index.php\" method=\"post\">";
                    echo "<input type=\"hidden\" name=\"load\" value=\"Savings/download\" />";
                    echo "<input type=\"hidden\" name=\"file_format\" value=\"json\" />";
                    echo "<input type=\"submit\" value=\"Descarca salvari ca JSON\" />";
                echo "</form>";
            echo "</div>";
        }
        

        if(!is_null($data)&&!empty($data)&&!is_array($data)){
            // echo "<p>Mesaj:$data</p>";
        }        

        // include("Footer.html"); 
    ?>
    <script src="views/javascript/navBar.js"></script>
    </body>
</html>
